apiVersion : apps/v1
kind : Deployment
metadata : 
  name : event-bus-defl
spec : 
  #number of pods that we want to create running particular image
  replicas : 1
  selector : 
    matchLabels:
      app : event-bus
  template : 
    metadata : 
      labels : 
        app : event-bus
    spec : 
      containers : 
        - name : event-bus
          image : justin1989kor/event-bus
---
apiVersion : v1
kind : Service
metadata :
  name : event-bus-srv
spec: 
  selector :
    app : event-bus
  ports : 
    - name : event-bus
      protocol : TCP
      port : 4005
      targetPort : 4005