apiVersion : apps/v1
kind : Deployment
metadata : 
  name : moderation-defl
spec : 
  #number of pods that we want to create running particular image
  replicas : 1
  selector : 
    matchLabels:
      app : moderation
  template : 
    metadata : 
      labels : 
        app : moderation
    spec : 
      containers : 
        - name : moderation
          image : justin1989kor/moderation
---
apiVersion : v1
kind : Service
metadata :
  name : moderation-srv
spec: 
  selector :
    app : moderation
  ports : 
    - name : moderation
      protocol : TCP
      port : 4003
      targetPort : 4003