apiVersion : apps/v1
kind : Deployment
metadata : 
  name : query-defl
spec : 
  #number of pods that we want to create running particular image
  replicas : 1
  selector : 
    matchLabels:
      app : query
  template : 
    metadata : 
      labels : 
        app : query
    spec : 
      containers : 
        - name : query
          image : justin1989kor/query
---
apiVersion : v1
kind : Service
metadata :
  name : query-srv
spec: 
  selector :
    app : query
  ports : 
    - name : query
      protocol : TCP
      port : 4002
      targetPort : 4002